# Preface {.unnumbered}

This document is our attempt at consolidating and sharing the detailed methods used to collect and analyze the indicator data presented in the California Current Ecosystem Status Report (ESR). The online technical documentation archive is designed to serve as a repository for the methods used to access, collect, process, and analyze the indicators presented in the report, while also reducing the length of the ESR and the redundancy among the annual reports.

The California Current ESR methods repository will be provided both as an online website <https://cciea-esr.github.io/ESR-Technical-Documentation-FY2027/> and a time-stamped Appendix (Appendix V) to the 2026-27 report, until it is reviewed by the SSC and Council. Thereafter, however, we intend for it to exist solely as an evolving online repository that documents changes to the indicator portfolio, the source data, and the methods used to derive them.

Chapters of this document are organized similarly to the structure of the ESR (i.e. one "chapter" of the technical documentation per section of the ESR). In some cases, we also may also include detailed methods for indicators that no longer are published in the most current version of the ESR document.

We thank the scientists at the Northeast Fisheries Science Center (DePiper et al. 2017) who provided the inspiration and initial template for some of this work <https://noaa-edab.github.io/tech-doc/index.html>. 
