# Objective {-}


The purpose of this document is to collate the methods used to access, collect, process, and analyze derived data (“indicators”) used to describe the status and trend of social, economic, ecological, and biological conditions in the California Current Large Marine Ecosystem (see [Fig. @fig-New_sampling_area_map], below). These indicators are further synthesized in Ecosystem Status Reports produced annually by the Northwest and Southwest Fisheries Science Centers for the Pacific Fisheries Management Council. The metadata for each indicator (in accordance with the Public Access to Research Results (PARR) directive) and the methods used to construct each indicator are described in the subsequent chapters, with each chapter title corresponding to an indicator or analysis present in Ecosystem Status Reports. The most recent and usable html version of this document can be found at <https://cciea-esr.github.io/ESR-Technical-Documentation-FY2027/>. The PDF version of this and future versions document will be archived in NOAA’s Institutional Repository.

Indicators included in this document were selected to clearly align with management objectives, which is required for integrated ecosystem assessment [@levin2009iea], and has been advised many times in the literature [@degnbol2004; @jennings2005; @rice2005; @link2005translating]. A difficulty with practical implementation of this in ecosystem reporting can be the lack of clearly specified ecosystem-level management objectives (although some have been suggested [@murawski2000]). In our case, considerable effort had already been applied to derive both general goals and operational objectives from both US legislation such as the Magnuson-Stevens Fisheries Conservation and Management Act (MSA) and regional sources [@harvey2021ecosystem].

**References**

::: {.sectionrefs}
:::

