---
title: "CCIEA ESR Technical Documentation"
format: gfm
---
**About the California Current Integrated Ecosystem Assessment (CCIEA) Ecosystem Status Report (ESR)**

* **CCIEA Web pages:** <https://www.integratedecosystemassessment.noaa.gov/regions/california-current>
* **Ecosystem Status Reports:** <https://www.integratedecosystemassessment.noaa.gov/regions/california-current/california-current-reports>

<hr>

**Where to find the Technical Documentation**

* **Version:** FY 2027 (reporting on data from 2026)
* **Technical Documentation Web page:** <https://cciea-esr.github.io/ESR-Technical-Documentation-FY2025/>
* **Download pdf:** <https://github.com/CCIEA-esr/ESR-Technical-Documentation-FY2027/blob/main/docs/CCIEA-ESR-Technical-Documentation.pdfZ

<hr>

**About**
The Technical Documentation for the annual CCIEA Ecosystem Status Report (ESR) is a Quarto document; hosted on the NOAA Northwest Fisheries Science Center (NWFSC) Github page, and developed in R.

The purpose of this document is to collate the methods used to access, collect, process, and analyze derived data (“indicators”) used to describe the status and trend of social, economic, ecological, and biological conditions in the California Current Large Marine Ecosystem (see figure, below). These indicators are further synthesized in Ecosystem Status Reports produced annually by the Northwest and Southwest Fisheries Science Centers for the Pacific Fisheries Management Council. The metadata for each indicator (in accordance with the Public Access to Research Results (PARR) directive) and the methods used to construct each indicator are described in the subsequent chapters, with each chapter title corresponding to an indicator or analysis present in Ecoystem Status Reports (i.e. one "chapter" of the technical documentation per section of the ESR). Also included are sections encompassing indicators that no longer are published in the most current version of the ESR document.

